<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mdeProject" nsURI="http://www.example.org/mdeProject" nsPrefix="mdeProject">
  <eClassifiers xsi:type="ecore:EClass" name="Presenter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="view" lowerBound="1" eType="#//View"
        eOpposite="#//View/presenter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1" eType="#//Model"
        eOpposite="#//Model/presenter"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="presenter" lowerBound="1"
        eType="#//Presenter" eOpposite="#//Presenter/model"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="View">
    <eStructuralFeatures xsi:type="ecore:EReference" name="presenter" lowerBound="1"
        eType="#//Presenter" eOpposite="#//Presenter/view"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MainPackage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subpackage" upperBound="-1"
        eType="#//SubPackage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubPackage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="presenter" upperBound="-1"
        eType="#//Presenter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" upperBound="-1"
        eType="#//Model" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subpackage" upperBound="-1"
        eType="#//SubPackage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="view" upperBound="-1" eType="#//View"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
